"""Persistence contracts; application code does not import SQLAlchemy."""

from typing import Protocol
from uuid import UUID

from lead_engine.domain.models import Company, Entity


class Repository(Protocol):
    def get[T: Entity](self, entity_type: type[T], entity_id: UUID) -> T | None: ...
    def list[T: Entity](self, entity_type: type[T], **filters: object) -> list[T]: ...
    def add(self, entity: Entity) -> None: ...
    def update_company(self, company: Company) -> None: ...
    def find_company_identity(self, key: str) -> Company | None: ...
    def add_company_identity(self, key: str, company_id: UUID) -> None: ...


class UnitOfWork(Protocol):
    @property
    def repository(self) -> Repository: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class DatabaseProbe(Protocol):
    def ping(self) -> None: ...
