"""contact research identities and runs
Revision ID: 0004
Revises: 0003
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import lead_engine.infrastructure.types

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact_identities",
        sa.Column("key", sa.String(length=1000), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_index(
        op.f("ix_contact_identities_contact_id"), "contact_identities", ["contact_id"], unique=False
    )
    op.create_table(
        "decision_maker_research_runs",
        sa.Column("lead_id", sa.Uuid(), nullable=True),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=1000), nullable=False),
        sa.Column(
            "started_at",
            lead_engine.infrastructure.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "finished_at",
            lead_engine.infrastructure.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("candidates_found", sa.Integer(), nullable=False),
        sa.Column("contacts_created", sa.Integer(), nullable=False),
        sa.Column("contacts_reused", sa.Integer(), nullable=False),
        sa.Column("conflicts", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=100), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "candidates_found >= 0 AND contacts_created >= 0 "
            "AND contacts_reused >= 0 AND conflicts >= 0",
            name="ck_contact_run_counts",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_decision_maker_research_runs_company_id"),
        "decision_maker_research_runs",
        ["company_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_decision_maker_research_runs_company_id"),
        table_name="decision_maker_research_runs",
    )
    op.drop_table("decision_maker_research_runs")
    op.drop_index(op.f("ix_contact_identities_contact_id"), table_name="contact_identities")
    op.drop_table("contact_identities")
    # ### end Alembic commands ###
