"""commercial brief history
Revision ID: 0005
Revises: 0004
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import lead_engine.infrastructure.types

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "commercial_briefs",
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column(
            "generated_at",
            lead_engine.infrastructure.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("research_version", sa.String(length=1000), nullable=False),
        sa.Column("lead_score_id", sa.Uuid(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lead_score_id"],
            ["lead_scores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_commercial_briefs_campaign_id"), "commercial_briefs", ["campaign_id"], unique=False
    )
    op.create_index(
        op.f("ix_commercial_briefs_company_id"), "commercial_briefs", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_commercial_briefs_generated_at"),
        "commercial_briefs",
        ["generated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_commercial_briefs_lead_id"), "commercial_briefs", ["lead_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_commercial_briefs_lead_id"), table_name="commercial_briefs")
    op.drop_index(op.f("ix_commercial_briefs_generated_at"), table_name="commercial_briefs")
    op.drop_index(op.f("ix_commercial_briefs_company_id"), table_name="commercial_briefs")
    op.drop_index(op.f("ix_commercial_briefs_campaign_id"), table_name="commercial_briefs")
    op.drop_table("commercial_briefs")
    # ### end Alembic commands ###
