"""daily shortlist history and suppressions
Revision ID: 0006
Revises: 0005
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import lead_engine.infrastructure.types

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_shortlist_runs",
        sa.Column(
            "generated_at",
            lead_engine.infrastructure.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("policy_version", sa.String(length=1000), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_daily_shortlist_runs_generated_at"),
        "daily_shortlist_runs",
        ["generated_at"],
        unique=False,
    )
    op.create_table(
        "shortlist_suppressions",
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column(
            "starts_at", lead_engine.infrastructure.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "expires_at",
            lead_engine.infrastructure.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column(
            "revoked_at", lead_engine.infrastructure.types.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("expires_at > starts_at", name="ck_shortlist_suppression_interval"),
        sa.CheckConstraint(
            "revoked_at IS NULL OR revoked_at >= starts_at", name="ck_shortlist_suppression_revoked"
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_shortlist_suppressions_lead_id"),
        "shortlist_suppressions",
        ["lead_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_shortlist_suppressions_lead_id"), table_name="shortlist_suppressions")
    op.drop_table("shortlist_suppressions")
    op.drop_index(op.f("ix_daily_shortlist_runs_generated_at"), table_name="daily_shortlist_runs")
    op.drop_table("daily_shortlist_runs")
    # ### end Alembic commands ###
