"""immutable outreach drafts and human decisions
Revision ID: 0007
Revises: 0006
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import lead_engine.infrastructure.types

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outreach_drafts",
        sa.Column("lead_id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=False),
        sa.Column("commercial_brief_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            lead_engine.infrastructure.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["commercial_brief_id"],
            ["commercial_briefs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_outreach_drafts_created_at"), "outreach_drafts", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_outreach_drafts_lead_id"), "outreach_drafts", ["lead_id"], unique=False
    )
    op.create_table(
        "outreach_events",
        sa.Column("draft_id", sa.Uuid(), nullable=False),
        sa.Column(
            "occurred_at",
            lead_engine.infrastructure.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=100), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=True),
        sa.Column("interaction_id", sa.Uuid(), nullable=True),
        sa.Column("actor", sa.String(length=1000), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('APPROVED','REJECTED','SUPERSEDED','USED')", name="ck_outreach_event_status"
        ),
        sa.CheckConstraint("sequence >= 1", name="ck_outreach_event_sequence"),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["outreach_drafts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["interaction_id"],
            ["lead_interactions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("draft_id", "sequence", name="uq_outreach_event_sequence"),
    )
    op.create_index(
        op.f("ix_outreach_events_draft_id"), "outreach_events", ["draft_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_outreach_events_draft_id"), table_name="outreach_events")
    op.drop_table("outreach_events")
    op.drop_index(op.f("ix_outreach_drafts_lead_id"), table_name="outreach_drafts")
    op.drop_index(op.f("ix_outreach_drafts_created_at"), table_name="outreach_drafts")
    op.drop_table("outreach_drafts")
    # ### end Alembic commands ###
