"""Stable business vocabulary; contacts carry no implicit decision-maker flag."""

from enum import StrEnum


class RoleCategory(StrEnum):
    OWNER = "OWNER"
    FOUNDER = "FOUNDER"
    GENERAL_MANAGEMENT = "GENERAL_MANAGEMENT"
    COMMERCIAL = "COMMERCIAL"
    MARKETING = "MARKETING"
    DIGITAL = "DIGITAL"
    CUSTOMER_EXPERIENCE = "CUSTOMER_EXPERIENCE"
    MEDICAL_DIRECTOR = "MEDICAL_DIRECTOR"
    ADMINISTRATION = "ADMINISTRATION"
    UNKNOWN = "UNKNOWN"


class SourceType(StrEnum):
    WEBSITE = "WEBSITE"
    GOOGLE_SEARCH = "GOOGLE_SEARCH"
    GOOGLE_MAPS = "GOOGLE_MAPS"
    LINKEDIN_PUBLIC = "LINKEDIN_PUBLIC"
    FACEBOOK_PUBLIC = "FACEBOOK_PUBLIC"
    INSTAGRAM_PUBLIC = "INSTAGRAM_PUBLIC"
    GOVERNMENT_REGISTRY = "GOVERNMENT_REGISTRY"
    BUSINESS_DIRECTORY = "BUSINESS_DIRECTORY"
    MANUAL = "MANUAL"
    OTHER = "OTHER"


class CampaignType(StrEnum):
    HEALTH = "HEALTH"
    CONSTRUCTION = "CONSTRUCTION"
    HOSPITALITY = "HOSPITALITY"


class LeadStatus(StrEnum):
    DISCOVERED = "DISCOVERED"
    QUALIFYING = "QUALIFYING"
    QUALIFIED = "QUALIFIED"
    REJECTED = "REJECTED"
    READY_FOR_RESEARCH = "READY_FOR_RESEARCH"
    READY_FOR_OUTREACH = "READY_FOR_OUTREACH"
    CONTACTED = "CONTACTED"
    RESPONDED = "RESPONDED"
    MEETING = "MEETING"
    PROPOSAL = "PROPOSAL"
    WON = "WON"
    LOST = "LOST"
    ARCHIVED = "ARCHIVED"


# A single state prevents disagreement between qualification and pipeline records.
PipelineStage = LeadStatus


class InteractionType(StrEnum):
    LINKEDIN_CONNECTION = "LINKEDIN_CONNECTION"
    LINKEDIN_MESSAGE = "LINKEDIN_MESSAGE"
    EMAIL = "EMAIL"
    WHATSAPP = "WHATSAPP"
    PHONE_CALL = "PHONE_CALL"
    MEETING = "MEETING"
    FOLLOW_UP = "FOLLOW_UP"
    PROPOSAL_SENT = "PROPOSAL_SENT"
    NOTE = "NOTE"
